title: Stackbit Vanilla Theme
baseURL: /
params:
  header:
    title: Visakh Vijayan
    has_nav: true
    nav_links:
      - label: Home
        url: /
      - label: Generic
        url: /generic/
      - label: Elements
        url: /elements/
      - label: Ipsum
        url: /ipsum/
  footer:
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=vanilla&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>
    has_social: true
    social_links:
      - label: Twitter
        url: 'https://twitter.com/vjnvisakh'
        new_window: true
      - label: GitHub
        url: 'https://github.com/visakhvjn'
        new_window: true
      - label: DEV
        url: 'https://dev.to/vjnvisakh'
        new_window: true
    links:
      - label: Generated from DEV
        url: 'https://dev.to/connecting-with-stackbit'
        new_window: true
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
